### ISSUE TITLE
[Improvement]: Compaitiblity with Pimcore 11

### ISSUE THREAD

**Issue by dpmR** [pimcore/image-tagging#6]
### Improvement description

Hey there, as this Bundle was not updated since 2020, are there any plans to make it compatible with Pimcore 11 or are there any alternatives?

**Comment by fashxp** [comment]
https://pimcore.com/docs/platform/Copilot_Showcases/Included_Actions/AI_Integrations_Powered_By_Hugging_Face/Hugging_Face_Fine-tune_Models#image-classification
